# Generated by Django 3.2.7 on 2021-10-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
